In [1]:
import pandas as pd

/opt/conda/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.0' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
import pandas as pd

In [7]:
df = pd.read_csv('COGS 164 Project Survey.csv')

In [9]:
df

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,"You're at work, and a colleague is visibly str...","While attending a music festival, you spot a c...","While walking through your neighborhood, you c...","At a school reunion, you see a former classmat...","While volunteering at a homeless shelter, you ...","While hiking in a remote area, you come across...",You're at a restaurant and you witness a custo...,Do you consider yourself more of an extrovert ...,Your insights are valuable to us. Would you be...,Do you consider yourself an empathetic/altruis...
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID30""}","{""ImportId"":""QID31""}","{""ImportId"":""QID32""}","{""ImportId"":""QID33""}","{""ImportId"":""QID34""}","{""ImportId"":""QID35""}","{""ImportId"":""QID36""}","{""ImportId"":""QID49""}","{""ImportId"":""QID38""}","{""ImportId"":""QID25_TEXT""}"
2,2024-02-27 14:14:47,2024-02-27 14:15:46,1,NaN,100,59,1,2024-02-27 14:15:48,R_3j0U5klcsf8h3gP,NaN,...,1,1,1,1,1,1,1,NaN,NaN,NaN
3,2024-02-27 14:34:40,2024-02-27 14:34:50,1,NaN,100,9,1,2024-02-27 14:34:51,R_3ToTVEAEw2n2o7L,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-02-27 14:35:23,2024-02-27 14:36:51,1,NaN,100,87,1,2024-02-27 14:36:52,R_3zNKp4fkwccObE6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2024-03-05 20:44:13,2024-03-05 20:51:57,0,70.95.179.223,100,464,1,2024-03-05 20:51:58,R_5fbBLhH4ebDUPst,NaN,...,4,3,5,4,4,5,5,2,1,Yes. Overcoming past traumas has helped me emp...
74,2024-03-05 20:44:59,2024-03-05 20:52:06,0,128.54.33.29,100,427,1,2024-03-05 20:52:06,R_3YIDJs3ePzSLqjT,NaN,...,4,3,4,4,4,4,4,2,1,"yes, I tend to feel strongly and am sympatheti..."
75,2024-03-05 22:18:50,2024-03-05 22:27:00,0,75.80.50.244,100,490,1,2024-03-05 22:27:01,R_1mgfRc8KcJOI1Ys,NaN,...,4,3,4,4,3,4,3,2,1,"I think of myself as an empathetic person, bec..."
76,2024-03-07 19:07:51,2024-03-07 19:11:45,0,75.102.135.243,100,233,1,2024-03-07 19:11:45,R_33klSoo76oUvkdc,NaN,...,4,4,2,1,3,4,5,2,1,I like to think that I am. I feel like most em...
77,2024-03-01 15:55:15,2024-03-01 15:57:52,0,138.229.251.65,48,157,0,2024-03-08 15:57:55,R_5EQBIy7QknbdBJY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.drop([0, 1])

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23
2,2024-02-27 14:14:47,2024-02-27 14:15:46,1,NaN,100,59,1,2024-02-27 14:15:48,R_3j0U5klcsf8h3gP,NaN,...,1,1,1,1,1,1,1,NaN,NaN,NaN
3,2024-02-27 14:34:40,2024-02-27 14:34:50,1,NaN,100,9,1,2024-02-27 14:34:51,R_3ToTVEAEw2n2o7L,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-02-27 14:35:23,2024-02-27 14:36:51,1,NaN,100,87,1,2024-02-27 14:36:52,R_3zNKp4fkwccObE6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2024-02-27 18:08:50,2024-02-27 18:09:19,1,NaN,100,29,1,2024-02-27 18:09:20,R_3OHqW0J8HRTNIoP,NaN,...,3,1,1,1,2,1,4,NaN,2,NaN
6,2024-02-27 19:29:55,2024-02-27 19:30:46,1,NaN,100,50,1,2024-02-27 19:30:48,R_6QWpi8ydddn4nUB,NaN,...,2,3,4,1,3,3,5,NaN,1,n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2024-03-05 20:44:13,2024-03-05 20:51:57,0,70.95.179.223,100,464,1,2024-03-05 20:51:58,R_5fbBLhH4ebDUPst,NaN,...,4,3,5,4,4,5,5,2,1,Yes. Overcoming past traumas has helped me emp...
74,2024-03-05 20:44:59,2024-03-05 20:52:06,0,128.54.33.29,100,427,1,2024-03-05 20:52:06,R_3YIDJs3ePzSLqjT,NaN,...,4,3,4,4,4,4,4,2,1,"yes, I tend to feel strongly and am sympatheti..."
75,2024-03-05 22:18:50,2024-03-05 22:27:00,0,75.80.50.244,100,490,1,2024-03-05 22:27:01,R_1mgfRc8KcJOI1Ys,NaN,...,4,3,4,4,3,4,3,2,1,"I think of myself as an empathetic person, bec..."
76,2024-03-07 19:07:51,2024-03-07 19:11:45,0,75.102.135.243,100,233,1,2024-03-07 19:11:45,R_33klSoo76oUvkdc,NaN,...,4,4,2,1,3,4,5,2,1,I like to think that I am. I feel like most em...
77,2024-03-01 15:55:15,2024-03-01 15:57:52,0,138.229.251.65,48,157,0,2024-03-08 15:57:55,R_5EQBIy7QknbdBJY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_1 = pd.read_csv('COGS 164 Project Survey_1.csv')

In [11]:
df_1

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,FL_3_DO
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,"While attending a music festival, you spot a c...","While walking through your neighborhood, you c...","At a school reunion, you see a former classmat...","While volunteering at a homeless shelter, you ...","While hiking in a remote area, you come across...",You're at a restaurant and you witness a custo...,Do you consider yourself more of an extrovert ...,Your insights are valuable to us. Would you be...,Do you consider yourself an empathetic/altruis...,FL_3 - Block Randomizer - Display Order
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID31""}","{""ImportId"":""QID32""}","{""ImportId"":""QID33""}","{""ImportId"":""QID34""}","{""ImportId"":""QID35""}","{""ImportId"":""QID36""}","{""ImportId"":""QID49""}","{""ImportId"":""QID38""}","{""ImportId"":""QID25_TEXT""}","{""ImportId"":""FL_3_DO""}"
2,2024-02-27 14:14:47,2024-02-27 14:15:46,1,NaN,100,59,1,2024-02-27 14:15:48,R_3j0U5klcsf8h3gP,NaN,...,1,1,1,1,1,1,NaN,NaN,NaN,SadManipulation
3,2024-02-27 14:34:40,2024-02-27 14:34:50,1,NaN,100,9,1,2024-02-27 14:34:51,R_3ToTVEAEw2n2o7L,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SadManipulation
4,2024-02-27 14:35:23,2024-02-27 14:36:51,1,NaN,100,87,1,2024-02-27 14:36:52,R_3zNKp4fkwccObE6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SadManipulation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2024-03-05 20:44:13,2024-03-05 20:51:57,0,70.95.179.223,100,464,1,2024-03-05 20:51:58,R_5fbBLhH4ebDUPst,NaN,...,3,5,4,4,5,5,2,1,Yes. Overcoming past traumas has helped me emp...,SadManipulation
74,2024-03-05 20:44:59,2024-03-05 20:52:06,0,128.54.33.29,100,427,1,2024-03-05 20:52:06,R_3YIDJs3ePzSLqjT,NaN,...,3,4,4,4,4,4,2,1,"yes, I tend to feel strongly and am sympatheti...",HappyManipulation
75,2024-03-05 22:18:50,2024-03-05 22:27:00,0,75.80.50.244,100,490,1,2024-03-05 22:27:01,R_1mgfRc8KcJOI1Ys,NaN,...,3,4,4,3,4,3,2,1,"I think of myself as an empathetic person, bec...",HappyManipulation
76,2024-03-07 19:07:51,2024-03-07 19:11:45,0,75.102.135.243,100,233,1,2024-03-07 19:11:45,R_33klSoo76oUvkdc,NaN,...,4,2,1,3,4,5,2,1,I like to think that I am. I feel like most em...,SadManipulation
77,2024-03-01 15:55:15,2024-03-01 15:57:52,0,138.229.251.65,48,157,0,2024-03-08 15:57:55,R_5EQBIy7QknbdBJY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HappyManipulation